// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeLock(arg1, arg2) {
  return window['go']['main']['App']['ChangeLock'](arg1, arg2);
}

export function CheckPin(arg1) {
  return window['go']['main']['App']['CheckPin'](arg1);
}

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectManaged(arg1) {
  return window['go']['main']['App']['ConnectManaged'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ForgetPassword(arg1) {
  return window['go']['main']['App']['ForgetPassword'](arg1);
}

export function ImportPath(arg1) {
  return window['go']['main']['App']['ImportPath'](arg1);
}

export function ImportText(arg1) {
  return window['go']['main']['App']['ImportText'](arg1);
}

export function InstallSetup(arg1, arg2) {
  return window['go']['main']['App']['InstallSetup'](arg1, arg2);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function Logs() {
  return window['go']['main']['App']['Logs']();
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function OpenSetupFile(arg1, arg2) {
  return window['go']['main']['App']['OpenSetupFile'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PinStatus() {
  return window['go']['main']['App']['PinStatus']();
}

export function ProvideCredentials(arg1) {
  return window['go']['main']['App']['ProvideCredentials'](arg1);
}

export function RemoveManaged() {
  return window['go']['main']['App']['RemoveManaged']();
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function TakePendingFiles() {
  return window['go']['main']['App']['TakePendingFiles']();
}

export function UnlockWithHello() {
  return window['go']['main']['App']['UnlockWithHello']();
}

export function UnlockWithPin(arg1) {
  return window['go']['main']['App']['UnlockWithPin'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}
