// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseFile():Promise<main.ImportResult>;

export function Connect(arg1:string,arg2:main.ConnectInput):Promise<void>;

export function ConnectManaged(arg1:main.ConnectInput):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ForgetPassword(arg1:string):Promise<void>;

export function ImportPath(arg1:string):Promise<main.ImportResult>;

export function ImportText(arg1:string):Promise<main.ImportResult>;

export function InstallSetup(arg1:string):Promise<void>;

export function Lock():Promise<void>;

export function Logs():Promise<Array<string>>;

export function OpenLink(arg1:number):Promise<void>;

export function OpenSetupFile(arg1:string,arg2:string):Promise<main.SetupSummary>;

export function OpenURL(arg1:string):Promise<void>;

export function PinStatus():Promise<main.UnlockResult>;

export function ProvideCredentials(arg1:main.ConnectInput):Promise<void>;

export function RemoveManaged():Promise<void>;

export function SaveDraft(arg1:string,arg2:main.ProfileInput):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function State():Promise<main.AppState>;

export function TakePendingFiles():Promise<Array<string>>;

export function TurnOffHello():Promise<void>;

export function UnlockWithHello():Promise<void>;

export function UnlockWithPin(arg1:string):Promise<main.UnlockResult>;

export function UpdateProfile(arg1:string,arg2:main.ProfileInput):Promise<void>;
